// frontend/rafikis-to-do-list/src/components/App.tsx
import React from 'react';
import {BrowserRouter as Router, Route } from "react-router-dom";
import List from './List';
import UserRegistration from './UserRegistration';


function App() {
  return (
    <Router>
      <Route path={["/", "/login"]} component={UserRegistration} exact></Route>
      <Route path="/signup" component={UserRegistration}></Route>
      <Route path="/list" component={List}></Route>
    </Router>
  );
}

export default App;

// mySvelte-Frontend/src/App.svelte
<script>

import { Router, Link, Route } from "svelte-routing";
import signUp from "./routes/signUp.svelte";
import login from "./routes/login.svelte";
import list from "./routes/list.svelte";
import item from "./routes/item/[id].svelte";

</script>
    
<style>		

</style>
    
<Router>
  <div>
    <Route path="" component="{login}" />
    <Route path="list" component="{list}" />
    <Route path="login" component="{login}" />
    <Route path="signUp" component="{signUp}" />
    <Route path="item/:id" component="{item}"/>
  </div>
</Router>
